# Pharmaceutical Product Matching — Data Cleaning & Normalization

**Goal:** prepare pharmaceutical product data for **product matching, equivalent-product identification, and price comparison**.

This notebook is **not an ML notebook**. It does not train a model, scale features, or create train/test sets.

### Principles
- Preserve all original columns.
- Create cleaned/engineered columns separately.
- Never translate Arabic drug names automatically.
- Use deterministic rules first.
- Use fuzzy matching only as a candidate/review step.
- Do not consider products equivalent based on active ingredient alone.

In [2]:
# Imports
import pandas as pd
import numpy as np
import re
import unicodedata
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

INPUT = Path("eg_drugs.csv")
OUTPUT = Path("eg_drugs_cleaned_product_matching.csv")

df = pd.read_csv(INPUT, dtype={"barcode": "string"})
work = df.copy()

print("Rows:", len(work))
print("Columns:", len(work.columns))
display(work.head())

Rows: 26562
Columns: 25

,id,name,arabic,active,company,price,oldprice,availability,barcode,slug,units,description,uses,matched_fda_ingredients,uses_summary,uses_summary_en,warning_high_blood_pressure,warning_diabetes,warning_pregnancy,warning_lactation,warning_kidney,warning_liver,warning_heart,warnings_summary,warnings_summary_en
0,1,1 2 3 (one two three) syrup 120 ml,ون تو ثري شراب 120 مل,Chlorpheniramine+paracetamol+pseudoephedrine,Hikma,40.00.,32.00.,NaN,6221000000010,1,1,Cold drugs,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,pseudoephedrine | chlorpheniramine,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,"temporarily relieves nasal congestion due to the common cold, hay fever or other upper respiratory allergies tempora...",1,1,1,1,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية، ارتفاع ضغط الدم، مرض السكري، أمراض ال...,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding, High Blood Pressure, D..."
1,2,1 2 3 (one two three) 20 f.c.tabs,ون تو ثري 20 قرص,Chlorpheniramine+paracetamol+pseudoephedrine,Hikma,40.00.,24.00.,NaN,6221000000010,2,2,Cold drugs,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,pseudoephedrine | chlorpheniramine,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,"temporarily relieves nasal congestion due to the common cold, hay fever or other upper respiratory allergies tempora...",1,1,1,1,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية، ارتفاع ضغط الدم، مرض السكري، أمراض ال...,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding, High Blood Pressure, D..."
2,3,5-fluorouracil-ebewe 250mg/5ml i.v. vial,فلورويوراسيل 250مجم/5مل فيال وريد,Fluorouracil,Shanghai xudong haipu pharmaceutical > acdima international trading,74.00.,50.00.,NaN,9088881320685,3,1,Antineoplastic,يُستخدم في علاج بعض أنواع سرطان القولون والمستقيم ويُعد من الأدوية الأساسية في بروتوكولات العلاج الكيماوي. يُستعمل ف...,fluorouracil,يُستخدم في علاج بعض أنواع سرطان القولون والمستقيم ويُعد من الأدوية الأساسية في بروتوكولات العلاج الكيماوي. يُستعمل ف...,Fluorouracil Cream is recommended for the topical treatment of multiple actinic or solar keratoses.,0,0,1,0,0,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل.,Caution or warning advised under medical supervision for: Pregnancy.
3,4,mooagar sachets,مو اجار 2جم اكياس,agar,hexa pharma company,75,NaN,3710.0,<NA>,mooagar-sachets,1,jaundice,الصفراء عند حديثي الولادة يُستخدم كمُليّن طبيعي لعلاج الإمساك، حيث يساعد على زيادة حجم البراز وتسهيل خروجه. يُستعمل ...,NaN,الصفراء عند حديثي الولادة يُستخدم كمُليّن طبيعي لعلاج الإمساك، حيث يساعد على زيادة حجم البراز وتسهيل خروجه. يُستعمل ...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.
4,5,limitless lactoferrin 100 mg 30 sachets,ليمتلس لاكتوفيرين 100 مجم 30 كيس,lactoferrin,eva pharma,485,385,3711.0,<NA>,limitless-lactoferrin-100-mg-30-sachets,1,iron supplement,يساعد في علاج الأنيميا الناتجة عن نقص الحديد لأنه يحسن امتصاص الحديد في الجسم. يساهم في تقوية جهاز المناعة ومقاومة ا...,NaN,يساعد في علاج الأنيميا الناتجة عن نقص الحديد لأنه يحسن امتصاص الحديد في الجسم. يساهم في تقوية جهاز المناعة ومقاومة ا...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.

## 1. Initial Data Quality Check

In [3]:
print("Shape:", work.shape)
print("\nData types:")
display(work.dtypes.to_frame("dtype"))

quality = pd.DataFrame({
    "dtype": work.dtypes.astype(str),
    "missing_count": work.isna().sum(),
    "missing_pct": (work.isna().mean() * 100).round(2),
    "unique_values": work.nunique(dropna=True)
}).sort_values("missing_count", ascending=False)

display(quality)
print("Exact duplicate rows:", work.duplicated().sum())

Shape: (26562, 25)

Data types:

                               dtype
id                             int64
name                             str
arabic                           str
active                           str
company                          str
price                            str
oldprice                         str
availability                 float64
barcode                       string
slug                             str
units                          int64
description                      str
uses                             str
matched_fda_ingredients          str
uses_summary                     str
uses_summary_en                  str
warning_high_blood_pressure    int64
warning_diabetes               int64
warning_pregnancy              int64
warning_lactation              int64
warning_kidney                 int64
warning_liver                  int64
warning_heart                  int64
warnings_summary                 str
warnings_summary_en              str

,dtype,missing_count,missing_pct,unique_values
uses,str,18455,69.48,5111
barcode,string,16030,60.35,10139
oldprice,str,15200,57.22,1383
matched_fda_ingredients,str,6980,26.28,5887
active,str,2757,10.38,9102
description,str,1135,4.27,2909
availability,float64,343,1.29,208
company,str,310,1.17,5533
price,str,5,0.02,2319
slug,str,1,0.00,26560
arabic,str,0,0.00,26403
id,int64,0,0.00,26562
name,str,0,0.00,26557
units,int64,0,0.00,25
uses_summary,str,0,0.00,6784
uses_summary_en,str,0,0.00,2640
warning_high_blood_pressure,int64,0,0.00,2
warning_diabetes,int64,0,0.00,2
warning_pregnancy,int64,0,0.00,2
warning_lactation,int64,0,0.00,2
warning_kidney,int64,0,0.00,2
warning_liver,int64,0,0.00,2
warning_heart,int64,0,0.00,2
warnings_summary,str,0,0.00,90
warnings_summary_en,str,0,0.00,90

Exact duplicate rows: 0

## 2. General Text Normalization

Arabic is preserved. Only conservative Unicode/whitespace normalization and selected Arabic variants are applied for matching-oriented fields.

In [4]:
def normalize_text(value, normalize_arabic=False, normalize_separators=False):
    if pd.isna(value):
        return pd.NA

    s = unicodedata.normalize("NFKC", str(value))
    s = s.replace("\u200f", "").replace("\u200e", "").replace("\ufeff", "")

    if normalize_arabic:
        # Conservative matching normalization; original value is untouched.
        s = s.translate(str.maketrans({
            "أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا", "ى": "ي"
        }))

    s = s.lower()
    s = re.sub(r"\s+", " ", s).strip()

    if normalize_separators:
        s = re.sub(r"\s*([,+|>/])\s*", r"\1", s)

    return s

text_rules = {
    "name": ("name_clean", True, True),
    "arabic": ("arabic_clean", True, False),
    "active": ("active_clean", False, True),
    "company": ("company_clean", True, True),
}

for src, (dst, arabic, separators) in text_rules.items():
    if src in work.columns:
        work[dst] = work[src].map(lambda x: normalize_text(x, arabic, separators))

display(work[[c for c in ["name", "name_clean", "arabic", "arabic_clean", "active", "active_clean", "company", "company_clean"] if c in work.columns]].head(10))

,name,name_clean,arabic,arabic_clean,active,active_clean,company,company_clean
0,1 2 3 (one two three) syrup 120 ml,1 2 3 (one two three) syrup 120 ml,ون تو ثري شراب 120 مل,ون تو ثري شراب 120 مل,Chlorpheniramine+paracetamol+pseudoephedrine,chlorpheniramine+paracetamol+pseudoephedrine,Hikma,hikma
1,1 2 3 (one two three) 20 f.c.tabs,1 2 3 (one two three) 20 f.c.tabs,ون تو ثري 20 قرص,ون تو ثري 20 قرص,Chlorpheniramine+paracetamol+pseudoephedrine,chlorpheniramine+paracetamol+pseudoephedrine,Hikma,hikma
2,5-fluorouracil-ebewe 250mg/5ml i.v. vial,5-fluorouracil-ebewe 250mg/5ml i.v. vial,فلورويوراسيل 250مجم/5مل فيال وريد,فلورويوراسيل 250مجم/5مل فيال وريد,Fluorouracil,fluorouracil,Shanghai xudong haipu pharmaceutical > acdima international trading,shanghai xudong haipu pharmaceutical>acdima international trading
3,mooagar sachets,mooagar sachets,مو اجار 2جم اكياس,مو اجار 2جم اكياس,agar,agar,hexa pharma company,hexa pharma company
4,limitless lactoferrin 100 mg 30 sachets,limitless lactoferrin 100 mg 30 sachets,ليمتلس لاكتوفيرين 100 مجم 30 كيس,ليمتلس لاكتوفيرين 100 مجم 30 كيس,lactoferrin,lactoferrin,eva pharma,eva pharma
5,plovimas mouth spray 60 ml,plovimas mouth spray 60 ml,بلوفيماس سبراي للفم 60 مل,بلوفيماس سبراي للفم 60 مل,des-infectant formula,des-infectant formula,NaN,NaN
6,a1 cream 100 gm,a1 cream 100 gm,ايه وان بيبي كريم 100جم,ايه وان بيبي كريم 100جم,castor oil+zinc oxide+arachis oil+bees wax,castor oil+zinc oxide+arachis oil+bees wax,egpi > egd,egpi>egd
7,limitless caffeine 80mg 20 oral dispersible films,limitless caffeine 80mg 20 oral dispersible films,ليميتلس كافيين 80مجم 20 فيلم,ليميتلس كافيين 80مجم 20 فيلم,caffeine,caffeine,eve pharma,eve pharma
8,no cal 300 packets,no cal 300 packets,نو كال 300 باكت,نو كال 300 باكت,sucralose+dextrose+maltodextrin,sucralose+dextrose+maltodextrin,NaN,NaN
9,canti colin syrup 100 ml,canti colin syrup 100 ml,كانتي كولين شراب 100 مل,كانتي كولين شراب 100 مل,citicoline,citicoline,pharma zad > cantreat,pharma zad>cantreat

## 3. Numeric / Barcode Cleaning

In [5]:
def clean_money(value):
    if pd.isna(value):
        return np.nan
    s = str(value).strip().replace(",", "")
    s = re.sub(r"\.+$", "", s)
    if re.fullmatch(r"[+-]?\d+(?:\.\d+)?", s):
        return float(s)
    return np.nan

def clean_barcode(value):
    if pd.isna(value):
        return pd.NA
    s = str(value).strip()
    # Convert Excel-like 123456789.0 without destroying leading zeros.
    if re.fullmatch(r"\d+\.0+", s):
        s = s.split(".")[0]
    return s or pd.NA

if "price" in work.columns:
    work["price_clean"] = work["price"].map(clean_money)
if "oldprice" in work.columns:
    work["oldprice_clean"] = work["oldprice"].map(clean_money)
if "availability" in work.columns:
    raw_availability = pd.to_numeric(work["availability"], errors="coerce")
    work["availability_clean"] = raw_availability.round().astype("Int64")
    work["negative_availability_flag"] = raw_availability.lt(0)
    work.loc[work["negative_availability_flag"], "availability_clean"] = pd.NA
if "barcode" in work.columns:
    work["barcode_clean"] = work["barcode"].map(clean_barcode).astype("string")
if "units" in work.columns:
    work["units_clean"] = pd.to_numeric(work["units"], errors="coerce").round().astype("Int64")

# Validation flags — do not silently fix questionable records.
if "price_clean" in work:
    work["price_invalid_flag"] = work["price"].notna() & work["price_clean"].isna()
if "oldprice_clean" in work:
    work["oldprice_invalid_flag"] = work["oldprice"].notna() & work["oldprice_clean"].isna()
if {"price_clean", "oldprice_clean"}.issubset(work.columns):
    work["oldprice_less_than_current_flag"] = (
        work["oldprice_clean"].notna() & work["price_clean"].notna() &
        work["oldprice_clean"].lt(work["price_clean"])
    )

if "barcode_clean" in work:
    work["barcode_format_flag"] = work["barcode_clean"].notna() & ~work["barcode_clean"].str.fullmatch(r"\d{8,14}", na=False)
    barcode_counts = work.loc[work["barcode_clean"].notna(), "barcode_clean"].value_counts()
    work["barcode_duplicate_flag"] = work["barcode_clean"].map(barcode_counts).fillna(0).gt(1)

display(work[[c for c in ["price", "price_clean", "oldprice", "oldprice_clean", "availability", "availability_clean", "barcode", "barcode_clean"] if c in work.columns]].head(10))

,price,price_clean,oldprice,oldprice_clean,availability,availability_clean,barcode,barcode_clean
0,40.00.,40.0,32.00.,32.0,NaN,<NA>,6221000000010,6221000000010
1,40.00.,40.0,24.00.,24.0,NaN,<NA>,6221000000010,6221000000010
2,74.00.,74.0,50.00.,50.0,NaN,<NA>,9088881320685,9088881320685
3,75,75.0,NaN,NaN,3710.0,3710,<NA>,<NA>
4,485,485.0,385,385.0,3711.0,3711,<NA>,<NA>
5,79,79.0,NaN,NaN,3621.0,3621,<NA>,<NA>
6,45,45.0,NaN,NaN,3837.0,3837,6223003930479,6223003930479
7,145,145.0,128,128.0,3496.0,3496,6223012483706,6223012483706
8,340,340.0,NaN,NaN,3789.0,3789,6224000843083,6224000843083
9,200,200.0,NaN,NaN,784.0,784,721688507246,721688507246

## 4. Active Ingredient Canonicalization

In [6]:
def canonical_active(value):
    if pd.isna(value) or not str(value).strip():
        return pd.NA

    parts = [p.strip() for p in re.split(r"\s*[+|,]\s*", str(value)) if p.strip()]
    # Sort only the ingredient tokens; this creates a canonical representation
    # for combinations where ingredient order does not define identity.
    return "+".join(sorted(dict.fromkeys(parts)))

if "active_clean" in work:
    work["active_canonical"] = work["active_clean"].map(canonical_active)

if "active_clean" in work:
    work["missing_active_flag"] = work["active_clean"].isna() | work["active_clean"].eq("")

## 5. Strength / Concentration / Volume Extraction

The parser distinguishes simple strength from concentration such as `5 mg/5 ml`. Multi-strength expressions such as `10/5/1000 mg` are preserved as a structured string.

In [7]:
NUM = r"(?:\d+(?:\.\d+)?|\.\d+)"
UNIT = r"(?:mg|mcg|µg|ug|g|kg|ng|iu|miu|mmol|mol|%|meq|kcal)"

concentration_pattern = re.compile(
    rf"({NUM})\s*({UNIT})\s*/\s*(?:(\d+(?:\.\d+)?)\s*)?(ml|l|g|kg|mg)\b", re.I
)
multi_strength_pattern = re.compile(rf"((?:{NUM}\s*/\s*)+{NUM})\s*({UNIT})\b", re.I)
single_strength_pattern = re.compile(rf"({NUM})\s*({UNIT})\b", re.I)

def normalize_unit(unit):
    return unit.lower().replace("µg", "mcg").replace("ug", "mcg")

def parse_dose(value):
    result = {
        "strength_value": np.nan,
        "strength_values": pd.NA,
        "strength_unit": pd.NA,
        "concentration_value": np.nan,
        "concentration_unit": pd.NA,
        "concentration_denominator_value": np.nan,
        "volume_value_from_concentration": np.nan,
        "volume_unit_from_concentration": pd.NA,
    }
    if pd.isna(value):
        return result

    s = str(value)
    m = concentration_pattern.search(s)
    if m:
        result.update({
            "concentration_value": float(m.group(1)),
            "concentration_unit": normalize_unit(m.group(2)),
            "concentration_denominator_value": float(m.group(3)) if m.group(3) else 1.0,
            "volume_value_from_concentration": float(m.group(3)) if m.group(3) else 1.0,
            "volume_unit_from_concentration": m.group(4).lower(),
        })
        return result

    m = multi_strength_pattern.search(s)
    if m:
        values = [float(x) for x in m.group(1).split("/")]
        normalized = "/".join(str(int(x)) if x.is_integer() else str(x) for x in values)
        result.update({
            "strength_value": values[0],
            "strength_values": normalized,
            "strength_unit": normalize_unit(m.group(2)),
        })
        return result

    m = single_strength_pattern.search(s)
    if m:
        value = float(m.group(1))
        result.update({
            "strength_value": value,
            "strength_values": str(int(value)) if value.is_integer() else str(value),
            "strength_unit": normalize_unit(m.group(2)),
        })
    return result

if "name_clean" in work:
    dose = pd.DataFrame(work["name_clean"].map(parse_dose).tolist(), index=work.index)
    for column in dose.columns:
        work[column] = dose[column]

## 6. Dosage Form, Route, Release Type, Pack Size and Volume

In [8]:
FORM_PATTERNS = [
    ("oral dispersible tablet", r"\b(?:oral\s+dispersible|odt)\s+(?:tablet|tablets|tab|tabs)\b"),
    ("tablet", r"\b(?:f\.?c\.?\s*)?(?:tablets?|tabs?)\b"),
    ("capsule", r"\b(?:capsules?|caps?)\b"),
    ("syrup", r"\bsyrups?\b"),
    ("suspension", r"\bsuspensions?\b"),
    ("solution", r"\bsolutions?\b"),
    ("injection", r"\b(?:injections?|inj)\b"),
    ("ampoule", r"\b(?:ampoules?|amps?|amp)\b"),
    ("vial", r"\bvials?\b"),
    ("cream", r"\bcreams?\b"),
    ("ointment", r"\bointments?\b"),
    ("gel", r"\bgels?\b"),
    ("drops", r"\bdrops?\b"),
    ("spray", r"\bsprays?\b"),
    ("suppository", r"\bsuppositories?\b"),
    ("sachet", r"\bsachets?\b"),
    ("oral film", r"\boral\s+(?:dispersible\s+)?films?\b"),
    ("powder", r"\bpowders?\b"),
    ("lozenge", r"\blozenges?\b"),
    ("patch", r"\bpatches?\b"),
    ("lotion", r"\blotions?\b"),
    ("shampoo", r"\bshampoos?\b"),
    ("mouthwash", r"\bmouthwash(?:es)?\b"),
]

def detect_form(value):
    if pd.isna(value):
        return "unknown"
    s = str(value)
    for form_name, pattern in FORM_PATTERNS:
        if re.search(pattern, s):
            return form_name
    return "unknown"

if "name_clean" in work:
    work["dosage_form"] = work["name_clean"].map(detect_form)

ROUTE_BY_FORM = {
    "tablet": "oral", "oral dispersible tablet": "oral", "capsule": "oral",
    "syrup": "oral", "suspension": "oral", "sachet": "oral", "oral film": "oral",
    "lozenge": "oral", "powder": "oral", "cream": "topical", "ointment": "topical",
    "gel": "topical", "lotion": "topical", "shampoo": "topical", "patch": "topical",
    "vial": "injectable", "ampoule": "injectable", "injection": "injectable",
}
work["route"] = work["dosage_form"].map(ROUTE_BY_FORM).fillna("unknown")

RELEASE_PATTERNS = [
    ("extended release", r"\b(?:extended|sustained|prolonged|controlled|modified)\s+release\b|\b(?:xr|er|sr|cr|mr)\b"),
    ("delayed release", r"\bdelayed\s+release\b|\bdr\b"),
    ("enteric coated", r"\benteric(?:-|\s+)coated\b|\be\.?c\.?\b"),
    ("immediate release", r"\bimmediate\s+release\b"),
]

def detect_release(value):
    if pd.isna(value):
        return "unknown"
    for release_name, pattern in RELEASE_PATTERNS:
        if re.search(pattern, str(value)):
            return release_name
    return "unknown"

work["release_type"] = work["name_clean"].map(detect_release)

FORM_WORDS = r"(?:tabs?|tablets?|caps?|capsules?|sachets?|vials?|amp(?:oules?)?|suppositories?|films?|lozenges?|patches?|bottles?)"

def extract_pack_size(value):
    if pd.isna(value):
        return np.nan
    s = str(value)
    patterns = [
        rf"\b(\d+)\s*(?:f\.?c\.?\s*)?{FORM_WORDS}\b",
        rf"\b{FORM_WORDS}\s*(?:x\s*)?(\d+)\b",
        r"\b(?:pack|box)\s*(?:of\s*)?(\d+)\b",
    ]
    for pattern in patterns:
        match = re.search(pattern, s)
        if match:
            return int(match.group(1))
    return np.nan

def extract_volume(value):
    if pd.isna(value):
        return np.nan, pd.NA
    matches = list(re.finditer(rf"\b({NUM})\s*(ml|l)\b", str(value), re.I))
    if not matches:
        return np.nan, pd.NA
    match = matches[-1]
    return float(match.group(1)), match.group(2).lower()

work["pack_size"] = work["name_clean"].map(extract_pack_size)
volume_df = pd.DataFrame(work["name_clean"].map(extract_volume).tolist(), columns=["volume_value", "volume_unit"], index=work.index)
work[["volume_value", "volume_unit"]] = volume_df

## 7. Product Matching Keys

Two levels are intentionally kept:
- **product_family_key:** same active/strength/form/route/release family, packaging may differ.
- **product_match_key:** stricter key for direct product/price comparison; packaging or volume is included.

These keys are deterministic and are not ML features.

In [9]:
LIQUID_FORMS = {"syrup", "suspension", "solution", "drops", "injection", "vial", "ampoule", "spray", "mouthwash"}

def dose_key(row):
    if pd.notna(row.get("concentration_value")):
        return (
            f"conc:{row['concentration_value']:g}:"
            f"{row['concentration_unit']}/"
            f"{row['concentration_denominator_value']:g}:"
            f"{row['volume_unit_from_concentration']}"
        )
    if pd.notna(row.get("strength_values")):
        return f"strength:{row['strength_values']}:{row['strength_unit']}"
    return None

def build_family_key(row):
    active = row.get("active_canonical")
    form = row.get("dosage_form")
    if pd.isna(active) or form == "unknown":
        return pd.NA
    dose = dose_key(row)
    if dose is None:
        return pd.NA
    return "|".join([str(active), dose, form, str(row.get("route", "unknown")), str(row.get("release_type", "unknown"))])

work["product_family_key"] = work.apply(build_family_key, axis=1)

def build_product_match_key(row):
    family = row.get("product_family_key")
    if pd.isna(family):
        return pd.NA

    form = row.get("dosage_form")
    if form in LIQUID_FORMS:
        if pd.isna(row.get("volume_value")) or pd.isna(row.get("volume_unit")):
            return pd.NA
        return f"{family}|volume:{row['volume_value']:g}:{row['volume_unit']}"

    if pd.isna(row.get("pack_size")):
        return pd.NA
    return f"{family}|pack:{int(row['pack_size'])}"

work["product_match_key"] = work.apply(build_product_match_key, axis=1)

print("Strict matching keys:", work["product_match_key"].notna().sum())
print("Family keys:", work["product_family_key"].notna().sum())

Strict matching keys: 7984
Family keys: 9795

## 8. Duplicate / Candidate Match Reports

In [10]:
# Exact duplicate rows
exact_duplicates = work[work.duplicated(keep=False)].copy()

# Same strict product key = strong candidate for same product/pack
product_duplicates = (
    work[work["product_match_key"].notna()]
    .loc[lambda x: x["product_match_key"].duplicated(keep=False)]
    .sort_values("product_match_key")
)

# Same family key = same normalized product family, but packaging may differ
family_duplicates = (
    work[work["product_family_key"].notna()]
    .loc[lambda x: x["product_family_key"].duplicated(keep=False)]
    .sort_values("product_family_key")
)

# Barcode duplicates
barcode_duplicates = work[work.get("barcode_duplicate_flag", False)].sort_values("barcode_clean") if "barcode_duplicate_flag" in work else pd.DataFrame()

print("Exact duplicate rows:", len(exact_duplicates))
print("Rows in repeated strict product keys:", len(product_duplicates))
print("Rows in repeated family keys:", len(family_duplicates))
print("Rows with duplicate barcodes:", len(barcode_duplicates))

display(product_duplicates.head(20))

Exact duplicate rows: 0
Rows in repeated strict product keys: 4796
Rows in repeated family keys: 7601
Rows with duplicate barcodes: 772

,id,name,arabic,active,company,price,oldprice,availability,barcode,slug,units,description,uses,matched_fda_ingredients,uses_summary,uses_summary_en,warning_high_blood_pressure,warning_diabetes,warning_pregnancy,warning_lactation,warning_kidney,warning_liver,warning_heart,warnings_summary,warnings_summary_en,name_clean,arabic_clean,active_clean,company_clean,price_clean,oldprice_clean,availability_clean,negative_availability_flag,barcode_clean,units_clean,price_invalid_flag,oldprice_invalid_flag,oldprice_less_than_current_flag,barcode_format_flag,barcode_duplicate_flag,active_canonical,missing_active_flag,strength_value,strength_values,strength_unit,concentration_value,concentration_unit,concentration_denominator_value,volume_value_from_concentration,volume_unit_from_concentration,dosage_form,route,release_type,pack_size,volume_value,volume_unit,product_family_key,product_match_key
23188,30066,zytiga 250 mg 120 tabs,زيتيجا 250مجم 120 اقراص,abiraterone acetate,janssen cilag > soficopharm,21685,NaN,0.0,<NA>,zytiga-250-mg-120-tabs,12,steroidal antiandrogen,NaN,abiraterone acetate,دواعي الاستعمال: 1 INDICATIONS AND USAGE Abiraterone acetate tablets are indicated in combination with prednisone fo...,1 INDICATIONS AND USAGE Abiraterone acetate tablets are indicated in combination with prednisone for the treatment o...,1,1,0,0,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: ارتفاع ضغط الدم، مرض السكري، أمراض القلب.,"Caution or warning advised under medical supervision for: High Blood Pressure, Diabetes, Heart Disease.",zytiga 250 mg 120 tabs,زيتيجا 250مجم 120 اقراص,abiraterone acetate,janssen cilag>soficopharm,21685.0,NaN,0,False,<NA>,12,False,False,False,False,False,abiraterone acetate,False,250.0,250,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,120.0,NaN,NaN,abiraterone acetate|strength:250:mg|tablet|oral|unknown,abiraterone acetate|strength:250:mg|tablet|oral|unknown|pack:120
23938,30862,mantroxate 250 mg 120 tabs,مانتروكسات 250مجم 120 قرص,abiraterone acetate,hikma specialized pharmaceuticals,26600,12853,0.0,<NA>,mantroxate-250-mg-120-tabs,1,steroidal antiandrogen,يعالج أبيراتيرون سرطان البروستاتا. ويعمل عن طريق خفض مستويات هرمون التستوستيرون في الجسم. وهذا يمنع خلايا سرطان البر...,abiraterone acetate,يعالج أبيراتيرون سرطان البروستاتا. ويعمل عن طريق خفض مستويات هرمون التستوستيرون في الجسم.,1 INDICATIONS AND USAGE Abiraterone acetate tablets are indicated in combination with prednisone for the treatment o...,1,1,0,0,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: ارتفاع ضغط الدم، مرض السكري، أمراض القلب.,"Caution or warning advised under medical supervision for: High Blood Pressure, Diabetes, Heart Disease.",mantroxate 250 mg 120 tabs,مانتروكسات 250مجم 120 قرص,abiraterone acetate,hikma specialized pharmaceuticals,26600.0,12853.0,0,False,<NA>,1,False,False,True,False,False,abiraterone acetate,False,250.0,250,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,120.0,NaN,NaN,abiraterone acetate|strength:250:mg|tablet|oral|unknown,abiraterone acetate|strength:250:mg|tablet|oral|unknown|pack:120
9649,13310,aceclocopa 100 mg 20 f.c. tab,اسيكلوكوبا 100 مجم 20 قرص,aceclofenac,copad pharma,22.5,NaN,0.0,6224000394226,aceclocopa-100-mg-20-f.c.-tab,2,nsaid.acetic acid derivatives,مسكن للالام -- خافض للحرارة -- تقليل الالتهابات والالام,NaN,مسكن للالام -- خافض للحرارة -- تقليل الالتهابات والالام.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,aceclocopa 100 mg 20 f.c. tab,اسيكلوكوبا 100 مجم 20 قرص,aceclofenac,copad pharma,22.5,NaN,0,False,6224000394226,2,False,False,False,False,False,aceclofenac,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,aceclofenac|strength:100:mg|tablet|oral|unknown,aceclofenac|strength:100:mg|tablet|oral|unknown|pack:20
9650,13311,aceliofinaz 100 mg 20 f.c. tab,اسيليوفيناز 100 مجم 20 قرص,aceclofenac,aug > people pharma,56,39,0.0,6224008819066,aceliofinaz-100-mg-20-f.c.-tab,2,nsaid.acetic acid derivatives,مسكن ومضاد للالتهابات وخافض للحرارة,NaN,مسكن ومضاد للالتهابات وخافض للحرارة.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,aceliofinaz 100 mg 20 f.c. tab,اسيليوفيناز 100 مجم 20 قرص,aceclofenac,aug>people pharma,56.0,39.0,0,False,6224008819066,2,False,False,True,False,False,aceclofenac,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,aceclofenac|strength:100:mg|tablet|oral|unknown,aceclofenac|strength:100:mg|tablet|oral|unknown|pack:20
11395,15496,bristaflam 100 mg 20 f.c.tabs,بريستفلام 100 مجم 20 قرص,aceclofenac,smithkline beecham,102,70,1.0,6224001007071,bristaflam-100-mg-20-f.c.tabs,2,nsaid.acetic acid derivatives,- الالتهابات الروماتيزمية للمفاصل. -- التهابات و آلام العظام. -- آلام الفقرات و الكتف و الركبتين. -- آلام العضلات ال...,NaN,- الالتهابات الروماتيزمية للمفاصل. -- التهابات و آلام العظام.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,bristaflam 100 mg 20 f.c.tabs,بريستفلام 100 مجم 20 قرص,aceclofenac,smithkline beecham,102.0,70.0,1,False,6224001007071,2,False,False,True,False,False,aceclofenac,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,aceclofenac|strength:100:mg|tablet|oral|unknown,aceclofenac|strength:100:mg|tablet|oral|unknown|pack:20
16136,21558,lambroflam 100 mg 20 f.c. tab,لامبروفلام 100مجم 20 قرص,aceclofenac,egpi > pioneer pharmaceutical industries,22.5,NaN,0.0,<NA>,lambroflam-100-mg-20-f.c.-tab,2,nsaid.acetic acid derivatives,NaN,NaN,لا توجد دواعي استعمال مسجلة.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,lambroflam 100 mg 20 f.c. tab,لامبروفلام 100مجم 20 قرص,aceclofenac,egpi>pioneer pharmaceutical industries,22.5,NaN,0,False,<NA>,2,False,False,False,False,False,aceclofenac,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,aceclofenac|strength:100:mg|tablet|oral|unknown,aceclofenac|strength:100:mg|tablet|oral|unknown|pack:20
26134,33402,pharma-flam 100 mg 20 f.c. tabs,فارما -فلام 100مجم 20 قرص,aceclofenac,elixir pharma,22.5,NaN,0.0,<NA>,pharma-flam-100-mg-20-f.c.-tabs,1,nsaid.acetic acid derivatives,NaN,NaN,لا توجد دواعي استعمال مسجلة.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,pharma-flam 100 mg 20 f.c. tabs,فارما -فلام 100مجم 20 قرص,aceclofenac,elixir pharma,22.5,NaN,0,False,<NA>,1,False,False,False,False,False,aceclofenac,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,aceclofenac|strength:100:mg|tablet|oral|unknown,aceclofenac|strength:100:mg|tablet|oral|unknown|pack:20
7837,9447,ost-map 60mg 20 caps,اوست-ماب 60 مجم 20 كبسولة,acemetacin,multi-apex,54,26,1.0,6223003204372,ost-map-60mg-20-caps,2,nsaid.analgesic,مسكن عام ومضاد التهاب,NaN,مسكن عام ومضاد التهاب.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,ost-map 60mg 20 caps,اوست-ماب 60 مجم 20 كبسولة,acemetacin,multi-apex,54.0,26.0,1,False,6223003204372,2,False,False,True,False,False,acemetacin,False,60.0,60,mg,NaN,NaN,NaN,NaN,NaN,capsule,oral,unknown,20.0,NaN,NaN,acemetacin|strength:60:mg|capsule|oral|unknown,acemetacin|strength:60:mg|capsule|oral|unknown|pack:20
9651,13312,acemetacin stada 60mg 20 caps,اسيميتاسين ستادا 60 مجم 20 كبسولة,acemetacin,adwia > stada,24,NaN,0.0,<NA>,acemetacin-stada-60mg-20-caps,2,nsaid.analgesic,NaN,NaN,لا توجد دواعي استعمال مسجلة.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,acemetacin stada 60mg 20 caps,اسيميتاسين ستادا 60 مجم 20 كبسولة,acemetacin,adwia>stada,24.0,NaN,0,False,<NA>,2,False,False,False,False,False,acemetacin,False,60.0,60,mg,NaN,NaN,NaN,NaN,NaN,capsule,oral,unknown,20.0,NaN,NaN,acemetacin|strength:60:mg|capsule|oral|unknown,acemetacin|strength:60:mg|capsule|oral|unknown|pack:20
2422,2559,cidamex 250mg 20 tab,سيدامكس 250مجم 20 قرص,acetazolamide,cid,60,44,6.0,6221043010571,cidamex-250mg-20-tab,2,diuretic.carbonic anhydrase inhibitors,لعلاج ارتفاع ضغط العين,acetazolamide,لعلاج ارتفاع ضغط العين.,For adjunctive treatment of: edema due to congestive heart failure; drug-induced edema; centrencephalic epilepsies (...,0,1,0,0,1,1,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: مرض السكري، أمراض القلب، أمراض الكلى، أمراض الكبد.,"Caution or warning advised under medical supervision for: Diabetes, Heart Disease, Kidney Disease, Liver Disease.",cidamex 250mg 20 tab,سيدامكس 250مجم 20 قرص,acetazolamide,cid,60.0,44.0,6,False,6221043010571,2,False,False,True,False,False,acetazolamide,False,250.0,250,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,acetazolamide|strength:250:mg|tablet|oral|unknown,acetazolamide|strength:250:mg|tablet|oral|unknown|pack:20
9654,13315,acetamex 250mg 20 tab,اسيتامكس 250مجم 20 قرص,acetazolamide,hi-pharm,6,NaN,0.0,<NA>,acetamex-250mg-20-tab,2,diuretic.carbonic anhydrase inhibitors,لعلاج ارتفاع ضغط العين IOP,acetazolamide,لعلاج ارتفاع ضغط العين IOP.,For adjunctive treatment of: edema due to congestive heart failure; drug-induced edema; centrencephalic epilepsies (...,0,1,0,0,1,1,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: مرض السكري، أمراض القلب، أمراض الكلى، أمراض الكبد.,"Caution or warning advised under medical supervision for: Diabetes, Heart Disease, Kidney Disease, Liver Disease.",acetamex 250mg 20 tab,اسيتامكس 250مجم 20 قرص,acetazolamide,hi-pharm,6.0,NaN,0,False,<NA>,2,False,False,False,False,False,acetazolamide,False,250.0,250,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,acetazolamide|strength:250:mg|tablet|oral|unknown,acetazolamide|strength:250:mg|tablet|oral|unknown|pack:20
48,49,acetylcistein 200 mg 10 sachet,استيل سيستايين فوار 200مجم 10 اكياس,acetylcysteine,sedico,55,30,416.0,6221042202014,acetylcistein-200-mg-10-sachet,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,acetylcistein 200 mg 10 sachet,استيل سيستايين فوار 200مجم 10 اكياس,acetylcysteine,sedico,55.0,30.0,416,False,6221042202014,1,False,False,True,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10
9256,12631,windy 200mg 10 sachet,ويندي 200مجم 10 اكياس فوار,acetylcysteine,pharco,25,14,0.0,6221151002321,windy-200mg-10-sachet,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,windy 200mg 10 sachet,ويندي 200مجم 10 اكياس فوار,acetylcysteine,pharco,25.0,14.0,0,False,6221151002321,1,False,False,True,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10
17323,23070,mucolator 200mg 10 sachet,ميوكولاتور 200مجم 10 اكياس,acetylcysteine,kahira > abbott laboratories,13.2,NaN,1.0,6221068201961,mucolator-200mg-10-sachet-,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,mucolator 200mg 10 sachet,ميوكولاتور 200مجم 10 اكياس,acetylcysteine,kahira>abbott laboratories,13.2,NaN,1,False,6221068201961,1,False,False,False,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10
23194,30073,acenewrax 200 mg 10 sachets,اسينيوراكس 200مجم 10 اكياس,acetylcysteine,jedco int. co. for pharmaceuticals > arax pharm. ind.,45,20,0.0,<NA>,acenewrax-200-mg-10-sachets,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,acenewrax 200 mg 10 sachets,اسينيوراكس 200مجم 10 اكياس,acetylcysteine,jedco int. co. for pharmaceuticals>arax pharm. ind.,45.0,20.0,0,False,<NA>,1,False,False,True,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10
25040,32105,flubronk 200mg 10 sachets,فلوبرونك 200مجم 10 اكياس,acetylcysteine,eipico,55,9,1.0,6221032163004,flubronk-200mg-10-sachets,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,flubronk 200mg 10 sachets,فلوبرونك 200مجم 10 اكياس,acetylcysteine,eipico,55.0,9.0,1,False,6221032163004,1,False,False,True,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10
23463,30358,cortopect 300 mg 30 caps,كورتوبكت 300مجم 30 كبسولة,acetylcysteine,> biomed,150,130,1.0,<NA>,cortopect-300-mg-30-caps,3,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,cortopect 300 mg 30 caps,كورتوبكت 300مجم 30 كبسولة,acetylcysteine,>biomed,150.0,130.0,1,False,<NA>,3,False,False,True,False,False,acetylcysteine,False,300.0,300,mg,NaN,NaN,NaN,NaN,NaN,capsule,oral,unknown,30.0,NaN,NaN,acetylcysteine|strength:300:mg|capsule|oral|unknown,acetylcysteine|strength:300:mg|capsule|oral|unknown|pack:30
23681,30589,gemacysteine 300 mg 30 caps,جيماسيستاين 300مجم 30 كبسولة,acetylcysteine,sedico > gema pharma,120,90,1.0,<NA>,gemacysteine-300-mg-30-caps,3,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,gemacysteine 300 mg 30 caps,جيماسيستاين 300مجم 30 كبسولة,acetylcysteine,sedico>gema pharma,120.0,90.0,1,False,<NA>,3,False,False,True,False,False,acetylcysteine,False,300.0,300,mg,NaN,NaN,NaN,NaN,NaN,capsule,oral,unknown,30.0,NaN,NaN,acetylcysteine|strength:300:mg|capsule|oral|unknown,acetylcysteine|strength:300:mg|capsule|oral|unknown|pack:30
4756,5415,windy 600 mg 10 sachet,ويندي 600 مجم 10 اكياس,acetylcysteine,pharco,70,35,0.0,<NA>,windy-600-mg-10-sachet,1,NaN,NaN,acetylcysteine,دواعي الاستعمال: 1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury a...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,windy 600 mg 10 sachet,ويندي 600 مجم 10 اكياس,acetylcysteine,pharco,70.0,35.0,0,False,<NA>,1,False,False,True,False,False,acetylcysteine,False,600.0,600,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:600:mg|sachet|oral|unknown,acetylcysteine|strength:600:mg|sachet|oral|unknown|pack:10
17318,23063,mucobrave 600 mg 10 sachets,ميوكوبراف فوار 600مجم 10 اكياس,acetylcysteine,xeedia pharma,75,50,7.0,6223002974856,mucobrave-600-mg-10-sachets,10,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,mucobrave 600 mg 10 sachets,ميوكوبراف فوار 600مجم 10 اكياس,acetylcysteine,xeedia pharma,75.0,50.0,7,False,6223002974856,10,False,False,True,False,False,acetylcysteine,False,600.0,600,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:600:mg|sachet|oral|unknown,acetylcysteine|strength:600:mg|sachet|oral|unknown|pack:10

## 9. Validation / Manual Review

Questionable values are flagged, not silently corrected.

In [11]:
review_flags = [c for c in [
    "price_invalid_flag", "oldprice_invalid_flag", "negative_availability_flag",
    "barcode_format_flag", "barcode_duplicate_flag", "oldprice_less_than_current_flag",
    "missing_name_flag", "missing_active_flag"
] if c in work.columns]

if "name_clean" in work:
    work["missing_name_flag"] = work["name_clean"].isna() | work["name_clean"].eq("")

review_mask = work[review_flags].any(axis=1) if review_flags else pd.Series(False, index=work.index)
validation_review = work.loc[review_mask].copy()

print("Records requiring review:", len(validation_review))
display(validation_review.head(20))

Records requiring review: 13360

,id,name,arabic,active,company,price,oldprice,availability,barcode,slug,units,description,uses,matched_fda_ingredients,uses_summary,uses_summary_en,warning_high_blood_pressure,warning_diabetes,warning_pregnancy,warning_lactation,warning_kidney,warning_liver,warning_heart,warnings_summary,warnings_summary_en,name_clean,arabic_clean,active_clean,company_clean,price_clean,oldprice_clean,availability_clean,negative_availability_flag,barcode_clean,units_clean,price_invalid_flag,oldprice_invalid_flag,oldprice_less_than_current_flag,barcode_format_flag,barcode_duplicate_flag,active_canonical,missing_active_flag,strength_value,strength_values,strength_unit,concentration_value,concentration_unit,concentration_denominator_value,volume_value_from_concentration,volume_unit_from_concentration,dosage_form,route,release_type,pack_size,volume_value,volume_unit,product_family_key,product_match_key,missing_name_flag
0,1,1 2 3 (one two three) syrup 120 ml,ون تو ثري شراب 120 مل,Chlorpheniramine+paracetamol+pseudoephedrine,Hikma,40.00.,32.00.,NaN,6221000000010,1,1,Cold drugs,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,pseudoephedrine | chlorpheniramine,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,"temporarily relieves nasal congestion due to the common cold, hay fever or other upper respiratory allergies tempora...",1,1,1,1,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية، ارتفاع ضغط الدم، مرض السكري، أمراض ال...,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding, High Blood Pressure, D...",1 2 3 (one two three) syrup 120 ml,ون تو ثري شراب 120 مل,chlorpheniramine+paracetamol+pseudoephedrine,hikma,40.0,32.0,<NA>,False,6221000000010,1,False,False,True,False,True,chlorpheniramine+paracetamol+pseudoephedrine,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,syrup,oral,unknown,NaN,120.0,ml,NaN,NaN,False
1,2,1 2 3 (one two three) 20 f.c.tabs,ون تو ثري 20 قرص,Chlorpheniramine+paracetamol+pseudoephedrine,Hikma,40.00.,24.00.,NaN,6221000000010,2,2,Cold drugs,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,pseudoephedrine | chlorpheniramine,تخفيف أعراض نزلات البرد والإنفلونزا مثل الصداع وارتفاع درجة الحرارة. يساعد في علاج احتقان الأنف والجيوب الأنفية وتحس...,"temporarily relieves nasal congestion due to the common cold, hay fever or other upper respiratory allergies tempora...",1,1,1,1,0,0,1,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية، ارتفاع ضغط الدم، مرض السكري، أمراض ال...,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding, High Blood Pressure, D...",1 2 3 (one two three) 20 f.c.tabs,ون تو ثري 20 قرص,chlorpheniramine+paracetamol+pseudoephedrine,hikma,40.0,24.0,<NA>,False,6221000000010,2,False,False,True,False,True,chlorpheniramine+paracetamol+pseudoephedrine,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,NaN,NaN,False
2,3,5-fluorouracil-ebewe 250mg/5ml i.v. vial,فلورويوراسيل 250مجم/5مل فيال وريد,Fluorouracil,Shanghai xudong haipu pharmaceutical > acdima international trading,74.00.,50.00.,NaN,9088881320685,3,1,Antineoplastic,يُستخدم في علاج بعض أنواع سرطان القولون والمستقيم ويُعد من الأدوية الأساسية في بروتوكولات العلاج الكيماوي. يُستعمل ف...,fluorouracil,يُستخدم في علاج بعض أنواع سرطان القولون والمستقيم ويُعد من الأدوية الأساسية في بروتوكولات العلاج الكيماوي. يُستعمل ف...,Fluorouracil Cream is recommended for the topical treatment of multiple actinic or solar keratoses.,0,0,1,0,0,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل.,Caution or warning advised under medical supervision for: Pregnancy.,5-fluorouracil-ebewe 250mg/5ml i.v. vial,فلورويوراسيل 250مجم/5مل فيال وريد,fluorouracil,shanghai xudong haipu pharmaceutical>acdima international trading,74.0,50.0,<NA>,False,9088881320685,1,False,False,True,False,False,fluorouracil,False,NaN,NaN,NaN,250.0,mg,5.0,5.0,ml,vial,injectable,unknown,NaN,5.0,ml,fluorouracil|conc:250:mg/5:ml|vial|injectable|unknown,fluorouracil|conc:250:mg/5:ml|vial|injectable|unknown|volume:5:ml,False
4,5,limitless lactoferrin 100 mg 30 sachets,ليمتلس لاكتوفيرين 100 مجم 30 كيس,lactoferrin,eva pharma,485,385,3711.0,<NA>,limitless-lactoferrin-100-mg-30-sachets,1,iron supplement,يساعد في علاج الأنيميا الناتجة عن نقص الحديد لأنه يحسن امتصاص الحديد في الجسم. يساهم في تقوية جهاز المناعة ومقاومة ا...,NaN,يساعد في علاج الأنيميا الناتجة عن نقص الحديد لأنه يحسن امتصاص الحديد في الجسم. يساهم في تقوية جهاز المناعة ومقاومة ا...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,limitless lactoferrin 100 mg 30 sachets,ليمتلس لاكتوفيرين 100 مجم 30 كيس,lactoferrin,eva pharma,485.0,385.0,3711,False,<NA>,1,False,False,True,False,False,lactoferrin,False,100.0,100,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,30.0,NaN,NaN,lactoferrin|strength:100:mg|sachet|oral|unknown,lactoferrin|strength:100:mg|sachet|oral|unknown|pack:30,False
7,8,limitless caffeine 80mg 20 oral dispersible films,ليميتلس كافيين 80مجم 20 فيلم,caffeine,eve pharma,145,128,3496.0,6223012483706,limitless-caffeine-80mg-20-oral-dispersible-films,1,cns.stimulant.methylxanthine,- يساعد على زيادة النشاط وتقليل الإحساس بالتعب والإرهاق. - يساعد على تحسين التركيز والانتباه خاصة أثناء المذاكرة أو ...,caffeine,- يساعد على زيادة النشاط وتقليل الإحساس بالتعب والإرهاق. - يساعد على تحسين التركيز والانتباه خاصة أثناء المذاكرة أو ...,helps restore mental alertness or wakefulness when experiencing fatigue or drowsiness.,0,0,1,1,0,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية.,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding.",limitless caffeine 80mg 20 oral dispersible films,ليميتلس كافيين 80مجم 20 فيلم,caffeine,eve pharma,145.0,128.0,3496,False,6223012483706,1,False,False,True,False,False,caffeine,False,80.0,80,mg,NaN,NaN,NaN,NaN,NaN,oral film,oral,unknown,NaN,NaN,NaN,caffeine|strength:80:mg|oral film|oral|unknown,NaN,False
10,11,abevac 1mg/ml vial,ابيفاك 1مجم فيال 1 مل,bee venom,vacsera,38,10,770.0,<NA>,abevac-1mg-ml-vial,1,vaccine,لقاح سم النحل • يُستخدم لعلاج حساسية لسعات النحل الشديدة وتقليل خطورة حدوث تفاعلات حساسية خطيرة. • يساعد الجسم على ت...,bee venom,لقاح سم النحل • يُستخدم لعلاج حساسية لسعات النحل الشديدة وتقليل خطورة حدوث تفاعلات حساسية خطيرة. • يساعد الجسم على ت...,"Removes common warts. Effective on warts on hands, feet, and skin (avoid face or genitals).",0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,abevac 1mg/ml vial,ابيفاك 1مجم فيال 1 مل,bee venom,vacsera,38.0,10.0,770,False,<NA>,1,False,False,True,False,False,bee venom,False,NaN,NaN,NaN,1.0,mg,1.0,1.0,ml,vial,injectable,unknown,NaN,NaN,NaN,bee venom|conc:1:mg/1:ml|vial|injectable|unknown,NaN,False
19,20,abilify 10 mg 10 tabs,ابيليفاي 10مجم 10 اقراص,aripiprazole,otsuka,220.5,176.5,590.0,6222014003547,abilify-10-mg-10-tabs,1,psychiatric.antipsychotics,* يستخدم في علاج الفصام (Schizophrenia) وتقليل الهلاوس والضلالات * يساعد في علاج نوبات الهوس المرتبطة باضطراب ثنائي ...,aripiprazole,* يستخدم في علاج الفصام (Schizophrenia) وتقليل الهلاوس والضلالات * يساعد في علاج نوبات الهوس المرتبطة باضطراب ثنائي ...,1 INDICATIONS AND USAGE Aripiprazole is indicated for the treatment of: • Schizophrenia • Irritability Associated wi...,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,abilify 10 mg 10 tabs,ابيليفاي 10مجم 10 اقراص,aripiprazole,otsuka,220.5,176.5,590,False,6222014003547,1,False,False,True,False,False,aripiprazole,False,10.0,10,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,10.0,NaN,NaN,aripiprazole|strength:10:mg|tablet|oral|unknown,aripiprazole|strength:10:mg|tablet|oral|unknown|pack:10,False
23,24,abimol 150mg/5ml syrup 125ml,ابيمول 150مجم/5مل 125 مل شراب,paracetamol(acetaminophen),glaxo smithkline,23,20,623.0,6221045000600,abimol-150mg-5ml-syrup-125ml,1,antipyretic.analgesic,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,NaN,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,abimol 150mg/5ml syrup 125ml,ابيمول 150مجم/5مل 125 مل شراب,paracetamol(acetaminophen),glaxo smithkline,23.0,20.0,623,False,6221045000600,1,False,False,True,False,False,paracetamol(acetaminophen),False,NaN,NaN,NaN,150.0,mg,5.0,5.0,ml,syrup,oral,unknown,NaN,125.0,ml,paracetamol(acetaminophen)|conc:150:mg/5:ml|syrup|oral|unknown,paracetamol(acetaminophen)|conc:150:mg/5:ml|syrup|oral|unknown|volume:125:ml,False
24,25,abimol 500 mg 20 tab,ابيمول 500مجم 20 قرص,paracetamol(acetaminophen),glaxo smithkline,24,13,848.0,6221045000341,abimol-500-mg-20-tab,2,antipyretic.analgesic,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,NaN,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,abimol 500 mg 20 tab,ابيمول 500مجم 20 قرص,paracetamol(acetaminophen),glaxo smithkline,24.0,13.0,848,False,6221045000341,2,False,False,True,False,False,paracetamol(acetaminophen),False,500.0,500,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,paracetamol(acetaminophen)|strength:500:mg|tablet|oral|unknown,paracetamol(acetaminophen)|strength:500:mg|tablet|oral|unknown|pack:20,False
25,26,abimol extra 20 tab,ابيمول اكسترا 500مجم 20 قرص,caffeine+paracetamol(acetaminophen),glaxo smithkline,28,16,601.0,6221045011101,abimol-extra-20-tab,2,analgesic.antipyretic.headache,مسكن للصداع بأنواعه خصوصًا الصداع النصفي والصداع الناتج عن التوتر تخفيف آلام الجسم العامة زي آلام العضلات والمفاصل ت...,caffeine,مسكن للصداع بأنواعه خصوصًا الصداع النصفي والصداع الناتج عن التوتر تخفيف آلام الجسم العامة زي آلام العضلات والمفاصل ت...,helps restore mental alertness or wakefulness when experiencing fatigue or drowsiness.,0,0,1,1,0,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية.,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding.",abimol extra 20 tab,ابيمول اكسترا 500مجم 20 قرص,caffeine+paracetamol(acetaminophen),glaxo smithkline,28.0,16.0,601,False,6221045011101,2,False,False,True,False,False,caffeine+paracetamol(acetaminophen),False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,20.0,NaN,NaN,NaN,NaN,False
26,27,abimol 300mg 5 rectal supp,ابيمول 300مجم لبوس 5 اقماع شرجية,paracetamol(acetaminophen),glaxo smithkline,15,6.5,599.0,6221045000808,abimol-300mg-5-rectal-supp,1,antipyretic.analgesic,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,NaN,1- يُستخدم كخافض للحرارة ومسكن فعال للألم في الحالات البسيطة والمتوسطة. 2- يساعد في خفض السخونة الناتجة عن نزلات الب...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,abimol 300mg 5 rectal supp,ابيمول 300مجم لبوس 5 اقماع شرجية,paracetamol(acetaminophen),glaxo smithkline,15.0,6.5,599,False,6221045000808,1,False,False,True,False,False,paracetamol(acetaminophen),False,300.0,300,mg,NaN,NaN,NaN,NaN,NaN,unknown,unknown,unknown,NaN,NaN,NaN,NaN,NaN,False
27,28,giraginine syrup 150 ml,جيراجينين شراب 150 مل,NaN,marvel,195,NaN,619.0,<NA>,giraginine-syrup-150-ml,1,multivitamin,NaN,NaN,لا توجد دواعي استعمال مسجلة.,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,giraginine syrup 150 ml,جيراجينين شراب 150 مل,NaN,marvel,195.0,NaN,619,False,<NA>,1,False,False,False,False,False,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,syrup,oral,unknown,NaN,150.0,ml,NaN,NaN,False
37,38,limitless prenatal max 30 tabs,ليميتلس برينيتال ماكس 30 قرص,vitamin a .. 650 mcg vitamin c .. 60 mg vitamin d3 ... 400 i.u. (10 mcg) vitamin e ... 30 i.u. (19 mg) thiamine ... ...,eva pharma,230,210,238.0,6223012483607,limitless-prenatal-max-30-tabs,3,multivitamin,تعويض نقص الفيتامينات في الجسم وسوء التغذية تقوية المناعة والوقاية من العدوى المتكررة تحسين صحة الشعر والبشرة والأظا...,NaN,تعويض نقص الفيتامينات في الجسم وسوء التغذية تقوية المناعة والوقاية من العدوى المتكررة تحسين صحة الشعر والبشرة والأظا...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,limitless prenatal max 30 tabs,ليميتلس برينيتال ماكس 30 قرص,vitamin a .. 650 mcg vitamin c .. 60 mg vitamin d3 ... 400 i.u. (10 mcg) vitamin e ... 30 i.u. (19 mg) thiamine ... ...,eva pharma,230.0,210.0,238,False,6223012483607,3,False,False,True,False,False,vitamin a .. 650 mcg vitamin c .. 60 mg vitamin d3 ... 400 i.u. (10 mcg) vitamin e ... 30 i.u. (19 mg) thiamine ... ...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,30.0,NaN,NaN,NaN,NaN,False
48,49,acetylcistein 200 mg 10 sachet,استيل سيستايين فوار 200مجم 10 اكياس,acetylcysteine,sedico,55,30,416.0,6221042202014,acetylcistein-200-mg-10-sachet,1,mucolytic,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,acetylcysteine,- مذيب قوي للبلغم وبيساعد على تفكيك المخاط في الشعب الهوائية - يُستخدم في حالات الكحة المصحوبة ببلغم سميك - مفيد لمر...,1 INDICATIONS AND USAGE Acetylcysteine Injection is indicated to prevent or lessen hepatic injury after ingestion of...,0,0,0,0,0,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكبد.,Caution or warning advised under medical supervision for: Liver Disease.,acetylcistein 200 mg 10 sachet,استيل سيستايين فوار 200مجم 10 اكياس,acetylcysteine,sedico,55.0,30.0,416,False,6221042202014,1,False,False,True,False,False,acetylcysteine,False,200.0,200,mg,NaN,NaN,NaN,NaN,NaN,sachet,oral,unknown,10.0,NaN,NaN,acetylcysteine|strength:200:mg|sachet|oral|unknown,acetylcysteine|strength:200:mg|sachet|oral|unknown|pack:10,False
49,50,allzyme max limitless 20 e.c. tab,اولزايم ماكس ليمتلس 20 قرص,bromelain+chemotrypsin+trypsin,eva pharma,155,145,413.0,6223007351959,allzyme-max-limitless-20-e.c.-tab,2,anti-inflammatory,- تقليل الالتهابات والتورم في حالات الإصابات والعمليات الجراحية - المساعدة في تسريع التئام الجروح وتحسين التعافي - ت...,bromelain | trypsin,- تقليل الالتهابات والتورم في حالات الإصابات والعمليات الجراحية - المساعدة في تسريع التئام الجروح وتحسين التعافي - ت...,: Bruselix™ Bruising Tablets are formulated to provide nutritional support during the body’s natural recovery process.,0,0,1,1,0,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، الرضاعة الطبيعية.,"Caution or warning advised under medical supervision for: Pregnancy, Lactation/Breastfeeding.",allzyme max limitless 20 e.c. tab,اولزايم ماكس ليمتلس 20 قرص,bromelain+chemotrypsin+trypsin,eva pharma,155.0,145.0,413,False,6223007351959,2,False,False,True,False,True,bromelain+chemotrypsin+trypsin,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tablet,oral,enteric coated,NaN,NaN,NaN,NaN,NaN,False
50,51,nercefaxon 1 gm i.v. vial,نيرسيفاكسون 1جم فيال للحقن وريد,ceftriaxone,badr pharma,56,26.5,239.0,6222018600025,nercefaxon-1-gm-i.v.-vial,1,antibiotic.cephalosporin.third-generation,مضاد حيوي قوي في علاج العديد من الالتهابات البكتيرية علاج التهابات الجهاز التنفسي مثل الالتهاب الرئوي علاج التهابات ...,ceftriaxone,مضاد حيوي قوي في علاج العديد من الالتهابات البكتيرية علاج التهابات الجهاز التنفسي مثل الالتهاب الرئوي علاج التهابات ...,"Before instituting treatment with ceftriaxone, appropriate specimens should be obtained for isolation of the causati...",0,0,1,0,1,1,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: الحمل، أمراض الكلى، أمراض الكبد.,"Caution or warning advised under medical supervision for: Pregnancy, Kidney Disease, Liver Disease.",nercefaxon 1 gm i.v. vial,نيرسيفاكسون 1جم فيال للحقن وريد,ceftriaxone,badr pharma,56.0,26.5,239,False,6222018600025,1,False,False,True,False,False,ceftriaxone,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vial,injectable,unknown,NaN,NaN,NaN,NaN,NaN,False
51,52,ranxapin 10 mg 7 tabs,رانكسابين 10مجم 7 قرص,olanzapine,future pharmaceutical industries(fpi) > sun pharma egypt limited,48.5,35,366.0,<NA>,ranxapin-10-mg-7-tabs,1,psychiatric.antipsychotics,علاج الأمراض والمشاكل النفسية مثل انفصام الشخصية. علاج الهوس المختلط أو حالات الهوس الحادة المصاحبة لمرض ثنائية القط...,olanzapine,علاج الأمراض والمشاكل النفسية مثل انفصام الشخصية. علاج الهوس المختلط أو حالات الهوس الحادة المصاحبة لمرض ثنائية القطب.,1 INDICATIONS AND USAGE Olanzapine is an atypical antipsychotic indicated: As oral formulation for the: Treatment of...,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,ranxapin 10 mg 7 tabs,رانكسابين 10مجم 7 قرص,olanzapine,future pharmaceutical industries(fpi)>sun pharma egypt limited,48.5,35.0,366,False,<NA>,1,False,False,True,False,False,olanzapine,False,10.0,10,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,7.0,NaN,NaN,olanzapine|strength:10:mg|tablet|oral|unknown,olanzapine|strength:10:mg|tablet|oral|unknown|pack:7,False
52,53,achtenon 2 mg 30 tabs,اكتينون 2مجم 30 قرص,biperidene,arab drug company.,51,34.5,291.0,6221060005239,achtenon-2-mg-30-tabs,3,antiparkinson agents. muscarinic antagonist.neuro,* يُستخدم لعلاج أعراض مرض باركنسون مثل الرعشة والتيبّس * يساعد في تقليل التصلب العضلي وتحسين الحركة * يُستعمل لعلاج ...,NaN,* يُستخدم لعلاج أعراض مرض باركنسون مثل الرعشة والتيبّس * يساعد في تقليل التصلب العضلي وتحسين الحركة * يُستعمل لعلاج ...,No registered indications.,0,0,0,0,0,0,0,لا توجد تحذيرات خاصة مسجلة لهذه الحالات. استشر الطبيب دائمًا.,No special warnings registered for these conditions. Always consult a doctor.,achtenon 2 mg 30 tabs,اكتينون 2مجم 30 قرص,biperidene,arab drug company.,51.0,34.5,291,False,6221060005239,3,False,False,True,False,False,biperidene,False,2.0,2,mg,NaN,NaN,NaN,NaN,NaN,tablet,oral,unknown,30.0,NaN,NaN,biperidene|strength:2:mg|tablet|oral|unknown,biperidene|strength:2:mg|tablet|oral|unknown|pack:30,False
54,55,aciclovir mylan 500 mg 5 vials,اسيكلوفير ميلان 500مجم 5 فيال,acyclovir,reig jofre-spain > ramco,755,520,281.0,<NA>,aciclovir-mylan-500-mg-5-vials,5,antiviral.nucleoside,- مضاد فيروسات لعلاج حالات العدوى الفيروسية - علاج عدوى فيروس الهربس البسيط (Herpes simplex) مثل الهربس الفموي والشف...,acyclovir,- مضاد فيروسات لعلاج حالات العدوى الفيروسية - علاج عدوى فيروس الهربس البسيط (Herpes simplex) مثل الهربس الفموي والشف...,Herpes Zoster Infections : Acyclovir is indicated for the acute treatment of herpes zoster (shingles).,0,0,0,0,1,0,0,يحذر أو يوصى بالحذر تحت إشراف طبي في الحالات التالية: أمراض الكلى.,Caution or warning advised under medical supervision for: Kidney Disease.,aciclovir mylan 500 mg 5 vials,اسيكلوفير ميلان 500مجم 5 فيال,acyclovir,reig jofre-spain>ramco,755.0,520.0,281,False,<NA>,5,False,False,True,False,False,acyclovir,False,500.0,500,mg,NaN,NaN,NaN,NaN,NaN,vial,injectable,unknown,5.0,NaN,NaN,acyclovir|strength:500:mg|vial|injectable|unknown,NaN,False

## 10. Price Comparison Helper

Use `product_match_key` for direct price comparison. Availability is checked separately because missing availability must not automatically mean unavailable.

In [12]:
def cheapest_available_products(data, product_match_key, min_availability=1):
    required = {"product_match_key", "price_clean", "availability_clean"}
    missing = required - set(data.columns)
    if missing:
        raise ValueError(f"Missing columns: {missing}")

    candidates = data[
        data["product_match_key"].eq(product_match_key) &
        data["price_clean"].notna() &
        data["availability_clean"].ge(min_availability)
    ].copy()

    return candidates.sort_values("price_clean")

# Example usage:
# key = work.loc[0, "product_match_key"]
# cheapest_available_products(work, key).head(10)

## 11. Export Clean Dataset and Reports

In [13]:
# Keep all original columns + cleaned/matching columns.
work.to_csv(OUTPUT, index=False, encoding="utf-8-sig")

exact_duplicates.to_csv("eg_drugs_exact_duplicates.csv", index=False, encoding="utf-8-sig")
product_duplicates.to_csv("eg_drugs_product_duplicates.csv", index=False, encoding="utf-8-sig")
family_duplicates.to_csv("eg_drugs_family_duplicates.csv", index=False, encoding="utf-8-sig")
barcode_duplicates.to_csv("eg_drugs_barcode_duplicates.csv", index=False, encoding="utf-8-sig")
validation_review.to_csv("eg_drugs_validation_review.csv", index=False, encoding="utf-8-sig")

print("Saved:", OUTPUT)
print("Final shape:", work.shape)

Saved: eg_drugs_cleaned_product_matching.csv
Final shape: (26562, 59)

## 12. Final Matching Rules

### Strong product match
Use `product_match_key` when available. It combines normalized active ingredients, strength/concentration, dosage form, route, release type, and packaging/volume.

### Product-family match
Use `product_family_key` when packaging differs or when the application needs to show products from the same family.

### Fuzzy matching
If a product has no exact key or name spelling is inconsistent, fuzzy matching can be used only to generate **candidate matches**. It should not automatically merge pharmaceutical records.

### Price comparison
Only compare prices after the products pass the appropriate matching rule. Then filter by valid numeric price and explicitly known positive availability.